os: osx
language: node_js
node_js:
  - '10'

cache:
  directories:
    - anvil-web/node_modules
    - anvil-web/dist

branches:
  only:
    - master

env:
  global:
    - NODE_ENV = production
    - TRAVIC = $TRAVIC

before_install:
  - cd anvil-web

install:
  - npm i

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $TOKEN
  keep-history: true
  local-dir: anvil-web/dist
  project-name: Anvil
  target-branch: deploy
  on:
    all_branches: true
