os: osx
language: node_js
node_js:
  - '10'

cache: npm

branches:
  only:
    - master

env:
  global:
    - NODE_ENV = production
    - TRAVIC = $TRAVIC

before_install:
  - cd anvil-web

install:
  - npm i

script:
  - npm run build

local-dir: avil-web/dist

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $TOKEN
  keep-history: true
  on:
    branch: deploy
